linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused

run:
  tests: true
  timeout: 5m

issues:
  max-same-issues: 10
  max-issues-per-linter: 0
  exclude-use-default: false
  exclude-dirs:
    - "internal/shared/repositories"
