// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package repositories

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/Toppira-Official/Reminder_Server/internal/shared/entities"
)

func newFirebaseSubscriber(db *gorm.DB, opts ...gen.DOOption) firebaseSubscriber {
	_firebaseSubscriber := firebaseSubscriber{}

	_firebaseSubscriber.firebaseSubscriberDo.UseDB(db, opts...)
	_firebaseSubscriber.firebaseSubscriberDo.UseModel(&entities.FirebaseSubscriber{})

	tableName := _firebaseSubscriber.firebaseSubscriberDo.TableName()
	_firebaseSubscriber.ALL = field.NewAsterisk(tableName)
	_firebaseSubscriber.Token = field.NewString(tableName, "token")
	_firebaseSubscriber.UserID = field.NewUint(tableName, "user_id")

	_firebaseSubscriber.fillFieldMap()

	return _firebaseSubscriber
}

type firebaseSubscriber struct {
	firebaseSubscriberDo firebaseSubscriberDo

	ALL    field.Asterisk
	Token  field.String
	UserID field.Uint

	fieldMap map[string]field.Expr
}

func (f firebaseSubscriber) Table(newTableName string) *firebaseSubscriber {
	f.firebaseSubscriberDo.UseTable(newTableName)
	return f.updateTableName(newTableName)
}

func (f firebaseSubscriber) As(alias string) *firebaseSubscriber {
	f.firebaseSubscriberDo.DO = *(f.firebaseSubscriberDo.As(alias).(*gen.DO))
	return f.updateTableName(alias)
}

func (f *firebaseSubscriber) updateTableName(table string) *firebaseSubscriber {
	f.ALL = field.NewAsterisk(table)
	f.Token = field.NewString(table, "token")
	f.UserID = field.NewUint(table, "user_id")

	f.fillFieldMap()

	return f
}

func (f *firebaseSubscriber) WithContext(ctx context.Context) IFirebaseSubscriberDo {
	return f.firebaseSubscriberDo.WithContext(ctx)
}

func (f firebaseSubscriber) TableName() string { return f.firebaseSubscriberDo.TableName() }

func (f firebaseSubscriber) Alias() string { return f.firebaseSubscriberDo.Alias() }

func (f firebaseSubscriber) Columns(cols ...field.Expr) gen.Columns {
	return f.firebaseSubscriberDo.Columns(cols...)
}

func (f *firebaseSubscriber) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := f.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (f *firebaseSubscriber) fillFieldMap() {
	f.fieldMap = make(map[string]field.Expr, 2)
	f.fieldMap["token"] = f.Token
	f.fieldMap["user_id"] = f.UserID
}

func (f firebaseSubscriber) clone(db *gorm.DB) firebaseSubscriber {
	f.firebaseSubscriberDo.ReplaceConnPool(db.Statement.ConnPool)
	return f
}

func (f firebaseSubscriber) replaceDB(db *gorm.DB) firebaseSubscriber {
	f.firebaseSubscriberDo.ReplaceDB(db)
	return f
}

type firebaseSubscriberDo struct{ gen.DO }

type IFirebaseSubscriberDo interface {
	gen.SubQuery
	Debug() IFirebaseSubscriberDo
	WithContext(ctx context.Context) IFirebaseSubscriberDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IFirebaseSubscriberDo
	WriteDB() IFirebaseSubscriberDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IFirebaseSubscriberDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IFirebaseSubscriberDo
	Not(conds ...gen.Condition) IFirebaseSubscriberDo
	Or(conds ...gen.Condition) IFirebaseSubscriberDo
	Select(conds ...field.Expr) IFirebaseSubscriberDo
	Where(conds ...gen.Condition) IFirebaseSubscriberDo
	Order(conds ...field.Expr) IFirebaseSubscriberDo
	Distinct(cols ...field.Expr) IFirebaseSubscriberDo
	Omit(cols ...field.Expr) IFirebaseSubscriberDo
	Join(table schema.Tabler, on ...field.Expr) IFirebaseSubscriberDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IFirebaseSubscriberDo
	RightJoin(table schema.Tabler, on ...field.Expr) IFirebaseSubscriberDo
	Group(cols ...field.Expr) IFirebaseSubscriberDo
	Having(conds ...gen.Condition) IFirebaseSubscriberDo
	Limit(limit int) IFirebaseSubscriberDo
	Offset(offset int) IFirebaseSubscriberDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IFirebaseSubscriberDo
	Unscoped() IFirebaseSubscriberDo
	Create(values ...*entities.FirebaseSubscriber) error
	CreateInBatches(values []*entities.FirebaseSubscriber, batchSize int) error
	Save(values ...*entities.FirebaseSubscriber) error
	First() (*entities.FirebaseSubscriber, error)
	Take() (*entities.FirebaseSubscriber, error)
	Last() (*entities.FirebaseSubscriber, error)
	Find() ([]*entities.FirebaseSubscriber, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entities.FirebaseSubscriber, err error)
	FindInBatches(result *[]*entities.FirebaseSubscriber, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*entities.FirebaseSubscriber) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IFirebaseSubscriberDo
	Assign(attrs ...field.AssignExpr) IFirebaseSubscriberDo
	Joins(fields ...field.RelationField) IFirebaseSubscriberDo
	Preload(fields ...field.RelationField) IFirebaseSubscriberDo
	FirstOrInit() (*entities.FirebaseSubscriber, error)
	FirstOrCreate() (*entities.FirebaseSubscriber, error)
	FindByPage(offset int, limit int) (result []*entities.FirebaseSubscriber, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IFirebaseSubscriberDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (f firebaseSubscriberDo) Debug() IFirebaseSubscriberDo {
	return f.withDO(f.DO.Debug())
}

func (f firebaseSubscriberDo) WithContext(ctx context.Context) IFirebaseSubscriberDo {
	return f.withDO(f.DO.WithContext(ctx))
}

func (f firebaseSubscriberDo) ReadDB() IFirebaseSubscriberDo {
	return f.Clauses(dbresolver.Read)
}

func (f firebaseSubscriberDo) WriteDB() IFirebaseSubscriberDo {
	return f.Clauses(dbresolver.Write)
}

func (f firebaseSubscriberDo) Session(config *gorm.Session) IFirebaseSubscriberDo {
	return f.withDO(f.DO.Session(config))
}

func (f firebaseSubscriberDo) Clauses(conds ...clause.Expression) IFirebaseSubscriberDo {
	return f.withDO(f.DO.Clauses(conds...))
}

func (f firebaseSubscriberDo) Returning(value interface{}, columns ...string) IFirebaseSubscriberDo {
	return f.withDO(f.DO.Returning(value, columns...))
}

func (f firebaseSubscriberDo) Not(conds ...gen.Condition) IFirebaseSubscriberDo {
	return f.withDO(f.DO.Not(conds...))
}

func (f firebaseSubscriberDo) Or(conds ...gen.Condition) IFirebaseSubscriberDo {
	return f.withDO(f.DO.Or(conds...))
}

func (f firebaseSubscriberDo) Select(conds ...field.Expr) IFirebaseSubscriberDo {
	return f.withDO(f.DO.Select(conds...))
}

func (f firebaseSubscriberDo) Where(conds ...gen.Condition) IFirebaseSubscriberDo {
	return f.withDO(f.DO.Where(conds...))
}

func (f firebaseSubscriberDo) Order(conds ...field.Expr) IFirebaseSubscriberDo {
	return f.withDO(f.DO.Order(conds...))
}

func (f firebaseSubscriberDo) Distinct(cols ...field.Expr) IFirebaseSubscriberDo {
	return f.withDO(f.DO.Distinct(cols...))
}

func (f firebaseSubscriberDo) Omit(cols ...field.Expr) IFirebaseSubscriberDo {
	return f.withDO(f.DO.Omit(cols...))
}

func (f firebaseSubscriberDo) Join(table schema.Tabler, on ...field.Expr) IFirebaseSubscriberDo {
	return f.withDO(f.DO.Join(table, on...))
}

func (f firebaseSubscriberDo) LeftJoin(table schema.Tabler, on ...field.Expr) IFirebaseSubscriberDo {
	return f.withDO(f.DO.LeftJoin(table, on...))
}

func (f firebaseSubscriberDo) RightJoin(table schema.Tabler, on ...field.Expr) IFirebaseSubscriberDo {
	return f.withDO(f.DO.RightJoin(table, on...))
}

func (f firebaseSubscriberDo) Group(cols ...field.Expr) IFirebaseSubscriberDo {
	return f.withDO(f.DO.Group(cols...))
}

func (f firebaseSubscriberDo) Having(conds ...gen.Condition) IFirebaseSubscriberDo {
	return f.withDO(f.DO.Having(conds...))
}

func (f firebaseSubscriberDo) Limit(limit int) IFirebaseSubscriberDo {
	return f.withDO(f.DO.Limit(limit))
}

func (f firebaseSubscriberDo) Offset(offset int) IFirebaseSubscriberDo {
	return f.withDO(f.DO.Offset(offset))
}

func (f firebaseSubscriberDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IFirebaseSubscriberDo {
	return f.withDO(f.DO.Scopes(funcs...))
}

func (f firebaseSubscriberDo) Unscoped() IFirebaseSubscriberDo {
	return f.withDO(f.DO.Unscoped())
}

func (f firebaseSubscriberDo) Create(values ...*entities.FirebaseSubscriber) error {
	if len(values) == 0 {
		return nil
	}
	return f.DO.Create(values)
}

func (f firebaseSubscriberDo) CreateInBatches(values []*entities.FirebaseSubscriber, batchSize int) error {
	return f.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (f firebaseSubscriberDo) Save(values ...*entities.FirebaseSubscriber) error {
	if len(values) == 0 {
		return nil
	}
	return f.DO.Save(values)
}

func (f firebaseSubscriberDo) First() (*entities.FirebaseSubscriber, error) {
	if result, err := f.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*entities.FirebaseSubscriber), nil
	}
}

func (f firebaseSubscriberDo) Take() (*entities.FirebaseSubscriber, error) {
	if result, err := f.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*entities.FirebaseSubscriber), nil
	}
}

func (f firebaseSubscriberDo) Last() (*entities.FirebaseSubscriber, error) {
	if result, err := f.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*entities.FirebaseSubscriber), nil
	}
}

func (f firebaseSubscriberDo) Find() ([]*entities.FirebaseSubscriber, error) {
	result, err := f.DO.Find()
	return result.([]*entities.FirebaseSubscriber), err
}

func (f firebaseSubscriberDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entities.FirebaseSubscriber, err error) {
	buf := make([]*entities.FirebaseSubscriber, 0, batchSize)
	err = f.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (f firebaseSubscriberDo) FindInBatches(result *[]*entities.FirebaseSubscriber, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return f.DO.FindInBatches(result, batchSize, fc)
}

func (f firebaseSubscriberDo) Attrs(attrs ...field.AssignExpr) IFirebaseSubscriberDo {
	return f.withDO(f.DO.Attrs(attrs...))
}

func (f firebaseSubscriberDo) Assign(attrs ...field.AssignExpr) IFirebaseSubscriberDo {
	return f.withDO(f.DO.Assign(attrs...))
}

func (f firebaseSubscriberDo) Joins(fields ...field.RelationField) IFirebaseSubscriberDo {
	for _, _f := range fields {
		f = *f.withDO(f.DO.Joins(_f))
	}
	return &f
}

func (f firebaseSubscriberDo) Preload(fields ...field.RelationField) IFirebaseSubscriberDo {
	for _, _f := range fields {
		f = *f.withDO(f.DO.Preload(_f))
	}
	return &f
}

func (f firebaseSubscriberDo) FirstOrInit() (*entities.FirebaseSubscriber, error) {
	if result, err := f.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*entities.FirebaseSubscriber), nil
	}
}

func (f firebaseSubscriberDo) FirstOrCreate() (*entities.FirebaseSubscriber, error) {
	if result, err := f.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*entities.FirebaseSubscriber), nil
	}
}

func (f firebaseSubscriberDo) FindByPage(offset int, limit int) (result []*entities.FirebaseSubscriber, count int64, err error) {
	result, err = f.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = f.Offset(-1).Limit(-1).Count()
	return
}

func (f firebaseSubscriberDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = f.Count()
	if err != nil {
		return
	}

	err = f.Offset(offset).Limit(limit).Scan(result)
	return
}

func (f firebaseSubscriberDo) Scan(result interface{}) (err error) {
	return f.DO.Scan(result)
}

func (f firebaseSubscriberDo) Delete(models ...*entities.FirebaseSubscriber) (result gen.ResultInfo, err error) {
	return f.DO.Delete(models)
}

func (f *firebaseSubscriberDo) withDO(do gen.Dao) *firebaseSubscriberDo {
	f.DO = *do.(*gen.DO)
	return f
}
